In [43]:
import requests
import json
import pandas as pd

fluctuo_docs = 'https://flow.fluctuo.com/docs'

fluctuo_token = 'ueddWWfQ2R9y1j3lzrPNI7Fj812fJyPS'

url = "https://flow-api.fluctuo.com/v1?access_token=" + fluctuo_token
head = {'content-type': 'application/json'}
data = {"query":"query ($lat: Float!, $lng: Float!) {\n  vehicles(lat: $lat, lng: $lng) {\n\t\tid\ttype\tlat\tlng\tlat\tpropulsion\tbattery\tattributes\tprovider\t{\n\t\tname\n}\n  }\n}","variables":{"lat":45.061122,"lng":7.686954}}

try:
    r = requests.post(url, data=json.dumps(data), headers=head) #converts a Python object into a json string
    r.raise_for_status()
except requests.exceptions.HTTPError as err:
    raise SystemExit(err)

r.status_code #check if the request is successful

200

In [44]:
json_data = r.json()

In [45]:
df_data = json_data['data']['vehicles']
df = pd.DataFrame(df_data)

In [46]:
df

,id,type,lat,lng,propulsion,battery,attributes,provider
0,Ym9sdDpTQ09PVEVSOjQ3MTQzNA==,SCOOTER,45.058571,7.690085,ELECTRIC,57.0,[ELECTRIC],{'name': 'Bolt'}
1,Ym9sdDpTQ09PVEVSOjQ3MTQ0Mg==,SCOOTER,45.063328,7.683782,ELECTRIC,59.0,[ELECTRIC],{'name': 'Bolt'}
2,Ym9sdDpTQ09PVEVSOjQ3MTQ0NQ==,SCOOTER,45.058792,7.690260,ELECTRIC,92.0,[ELECTRIC],{'name': 'Bolt'}
3,Ym9sdDpTQ09PVEVSOjQ3MTg4Mw==,SCOOTER,45.060246,7.683962,ELECTRIC,49.0,[ELECTRIC],{'name': 'Bolt'}
4,Ym9sdDpTQ09PVEVSOjQ3MjAzNQ==,SCOOTER,45.061066,7.688470,ELECTRIC,56.0,[ELECTRIC],{'name': 'Bolt'}
5,Ym9sdDpTQ09PVEVSOjQ3MjA4Ng==,SCOOTER,45.059097,7.687945,ELECTRIC,35.0,[ELECTRIC],{'name': 'Bolt'}
6,Ym9sdDpTQ09PVEVSOjQ3MjA4OA==,SCOOTER,45.059288,7.686131,ELECTRIC,45.0,[ELECTRIC],{'name': 'Bolt'}
7,Ym9sdDpTQ09PVEVSOjQ3MjE0NA==,SCOOTER,45.063469,7.685512,ELECTRIC,25.0,[ELECTRIC],{'name': 'Bolt'}
8,Ym9sdDpTQ09PVEVSOjQ3MjI4MQ==,SCOOTER,45.058468,7.684785,ELECTRIC,27.0,[ELECTRIC],{'name': 'Bolt'}
9,aGVsYml6OlNDT09URVI6QzhVOFo4,SCOOTER,45.061322,7.688723,ELECTRIC,NaN,[],{'name': 'Helbiz'}
10,aGVsYml6OlNDT09URVI6STZLNEE2,SCOOTER,45.062253,7.686233,ELECTRIC,NaN,[],{'name': 'Helbiz'}
11,aGVsYml6OlNDT09URVI6WjhDOUs5,SCOOTER,45.061200,7.687068,ELECTRIC,NaN,[],{'name': 'Helbiz'}
12,aGVsYml6OlNDT09URVI6STlPOVE3,SCOOTER,45.061702,7.687792,ELECTRIC,NaN,[],{'name': 'Helbiz'}
13,aGVsYml6OlNDT09URVI6RzNHNVIw,SCOOTER,45.061685,7.687840,ELECTRIC,NaN,[],{'name': 'Helbiz'}
14,bGluazpTQ09PVEVSOmZjZTc4YzA3LWUzMDAtNGM2Yy05Mm...,SCOOTER,45.058730,7.690370,ELECTRIC,85.0,None,{'name': 'Link'}
15,bGluazpTQ09PVEVSOmM3ZWI2NDdjLWM0OTUtNDNiNC1iMz...,SCOOTER,45.058540,7.685760,ELECTRIC,32.0,None,{'name': 'Link'}
16,bGluazpTQ09PVEVSOjNlMmUyZjE2LTdlNDktNDFkZS04ZW...,SCOOTER,45.059360,7.687610,ELECTRIC,62.0,None,{'name': 'Link'}
17,dGllcjpTQ09PVEVSOmRlYjZkZWVjLTQ2MGItNGY5MC1hYW...,SCOOTER,45.059109,7.687801,ELECTRIC,59.0,[ELECTRIC],{'name': 'Tier'}
18,dGllcjpTQ09PVEVSOjE4ZmRjNWVjLWQ0Y2ItNDY5My1hOD...,SCOOTER,45.064134,7.686276,ELECTRIC,100.0,[ELECTRIC],{'name': 'Tier'}
19,dGllcjpTQ09PVEVSOjU0NGZhYzY1LWU2ZWYtNGE2Yy1hZT...,SCOOTER,45.059286,7.687702,ELECTRIC,21.0,[ELECTRIC],{'name': 'Tier'}
20,dGllcjpTQ09PVEVSOjE4MjE3ZmRjLTJhOGUtNGFjZC1iMD...,SCOOTER,45.063979,7.686503,ELECTRIC,96.0,[ELECTRIC],{'name': 'Tier'}
21,dGllcjpTQ09PVEVSOjFkOGZlN2U1LTdlZGYtNGM0Zi1iZj...,SCOOTER,45.060663,7.690268,ELECTRIC,63.0,[ELECTRIC],{'name': 'Tier'}
22,dGllcjpTQ09PVEVSOmMzNTFhN2JkLWQ1OTAtNDY0Ni1hOG...,SCOOTER,45.060340,7.683100,ELECTRIC,79.0,[ELECTRIC],{'name': 'Tier'}
23,dG9iaWtlOlNUQVRJT046MzEz,STATION,45.063371,7.684235,None,NaN,None,{'name': '[TO]Bike'}
24,dG9iaWtlOlNUQVRJT046MzU3,STATION,45.061593,7.682342,None,NaN,None,{'name': '[TO]Bike'}
25,dm9pOlNDT09URVI6Y2E4YmY5ZjYtOGZmOC00ZTI5LWEyNT...,SCOOTER,45.059196,7.685484,ELECTRIC,77.0,[ELECTRIC],{'name': 'Voi'}
26,dm9pOlNDT09URVI6Y2FhNzc4ZDEtOGVjYS00ZDQ0LWFjND...,SCOOTER,45.058380,7.690422,ELECTRIC,69.0,[ELECTRIC],{'name': 'Voi'}
27,dm9pOlNDT09URVI6YTdlOGQ1ZDgtYTAxZi00MmQxLTk1MD...,SCOOTER,45.061108,7.683450,ELECTRIC,32.0,[ELECTRIC],{'name': 'Voi'}
28,dm9pOlNDT09URVI6ZjUxNzVhYjQtMTM4My00OTQ0LWJlZG...,SCOOTER,45.059029,7.684468,ELECTRIC,57.0,[ELECTRIC],{'name': 'Voi'}
29,dm9pOlNDT09URVI6MGQ1MDAwNDItOTkwMy00MjA2LTk4YT...,SCOOTER,45.061665,7.687981,ELECTRIC,87.0,[ELECTRIC],{'name': 'Voi'}
30,dm9pOlNDT09URVI6YWU5MjU3MzQtMjg4OS00NTQwLTlmMj...,SCOOTER,45.059158,7.687919,ELECTRIC,94.0,[ELECTRIC],{'name': 'Voi'}
31,dm9pOlNDT09URVI6ZjFhOGI3M2UtZmZkMy00MGZhLWI5YT...,SCOOTER,45.063435,7.688803,ELECTRIC,89.0,[ELECTRIC],{'name': 'Voi'}
32,dm9pOlNDT09URVI6ZWY4NzhmMDgtNWZkNS00YjMxLWE5MG...,SCOOTER,45.059605,7.687686,ELECTRIC,81.0,[ELECTRIC],{'name': 'Voi'}
33,dm9pOlNDT09URVI6OGU1M2M3ODItZTNkYi00MWQ4LTgwNW...,SCOOTER,45.061699,7.687967,ELECTRIC,88.0,[ELECTRIC],{'name': 'Voi'}